theme: jekyll-theme-cayman
title: OpenSolvers
description: RISC-V learnings and fun

navigation:
  - title: Home
    url: /
  - title: VisionFive 2
    url: /boards/VisionFive2.html
  - title: OrangePi RV2
    url: /boards/RV2.html
  - title: BananaPi F3
    url: /boards/F3.html
